### ISSUE TITLE
Storage partition isn't working as intended 

### ISSUE THREAD

**Issue by jagadeeshaby** [wanderview/quota-storage-partitioning#12]
Definition says Storage partition is applied to TLD (top level domain like .com) + 1, but we are observing a scenario where it isn't the case. Like for the top level site [lightning.force.com](http://lightning.force.com/) and [vf.force.com](http://vf.force.com/) , we are observing 2 shared worker getting spun up instead of one.

Please advice.

**Comment by sbingler** [comment]
Hi jagadeeshaby,

To help us resolve your issue, can you please visit https://bugs.chromium.org/p/chromium/issues/detail?id=1502258 and answer the questions I posted there?

Thanks

**Comment by miketaylr** [comment]
Closing this issue in favor of the crbug (which is a better place to report browser-specific issues).

**Comment by jagadeeshaby** [comment]
Thank you!
