### ISSUE TITLE
Standarization of the API

### ISSUE THREAD

**Issue by jcubic** [wanderview/quota-storage-partitioning#13]
Are there any efforts to make this feature a standard of some kind, maybe in HTML Living Standard?
I'm asking because it would be nice to get the same behavior in Safari where Cross-Domain communication with iframe doesn't work even for a subdomain (which works with storage partitioning in Chrome).

I'm asking this as a maintainer for a library [sysend.js](https://github.com/jcubic/sysend.js).

**Comment by wanderview** [comment]
Yes, you can see some pull requests like:

https://github.com/whatwg/storage/pull/144
https://github.com/whatwg/html/pull/8027
https://github.com/whatwg/html/pull/8036

But its currently blocked on some html spec refactoring.
