### ISSUE TITLE
Access to partitioned storage while blocking 3P cookies

### ISSUE THREAD

**Issue by bailer** [wanderview/quota-storage-partitioning#7]
Most (if not all?) storage APIs seems to be blocked when Chrome is set to block 3P cookies, which makes sense since other types of storages could be abused to circumvent the blocking of 3P cookies to still share state between first party and third party contexts.

With the introduction of partitioned storages in third party contexts, I was hoping that the storage APIs would become available in third party contexts even when 3P cookies are disabled in order to persist useful state per third party context but when enabling the [flag](chrome://flags/#third-party-storage-partitioning) it seems like the storage APIs are still disabled while Chrome is blocking 3P cookies even though the storages are partitioned.

Is this the intended behaviour?

**Comment by miketaylr** [comment]
Hey @bailer - yep, that work is currently in progress. You can follow along at https://bugs.chromium.org/p/chromium/issues/detail?id=1453783.

**Comment by bailer** [comment]
Ok cool, thanks for the quick response!

**Comment by miketaylr** [comment]
Note for others, as of Chrome 119, if a user blocks 3P cookies they will have access to partitioned storage in 3P contexts (rather than have storage blocked).
